[2025-01-24T23:04:01.088+0000] {processor.py:186} INFO - Started process (PID=67) to work on /opt/airflow/dags/dag.py
[2025-01-24T23:04:01.090+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-01-24T23:04:01.100+0000] {logging_mixin.py:190} INFO - [2025-01-24T23:04:01.099+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-01-24T23:04:01.140+0000] {logging_mixin.py:190} INFO - [2025-01-24T23:04:01.132+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 11, in <module>
    prim_pipeline_dag = prim_pipelines()
                        ^^^^^^^^^^^^^^^^
TypeError: dag.<locals>.wrapper() missing 1 required positional argument: 'f'
[2025-01-24T23:04:01.143+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-01-24T23:04:01.191+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.119 seconds
[2025-01-24T23:04:31.694+0000] {processor.py:186} INFO - Started process (PID=74) to work on /opt/airflow/dags/dag.py
[2025-01-24T23:04:31.696+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-01-24T23:04:31.707+0000] {logging_mixin.py:190} INFO - [2025-01-24T23:04:31.706+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-01-24T23:04:31.738+0000] {logging_mixin.py:190} INFO - [2025-01-24T23:04:31.731+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 11, in <module>
    prim_pipeline_dag = prim_pipelines()
                        ^^^^^^^^^^^^^^^^
TypeError: dag.<locals>.wrapper() missing 1 required positional argument: 'f'
[2025-01-24T23:04:31.741+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-01-24T23:04:31.792+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.137 seconds
[2025-01-24T23:05:02.084+0000] {processor.py:186} INFO - Started process (PID=81) to work on /opt/airflow/dags/dag.py
[2025-01-24T23:05:02.086+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-01-24T23:05:02.092+0000] {logging_mixin.py:190} INFO - [2025-01-24T23:05:02.091+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-01-24T23:05:02.116+0000] {logging_mixin.py:190} INFO - [2025-01-24T23:05:02.109+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 11, in <module>
    prim_pipeline_dag = prim_pipelines()
                        ^^^^^^^^^^^^^^^^
TypeError: dag.<locals>.wrapper() missing 1 required positional argument: 'f'
[2025-01-24T23:05:02.118+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-01-24T23:05:02.152+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.084 seconds
[2025-01-24T23:05:34.731+0000] {processor.py:186} INFO - Started process (PID=88) to work on /opt/airflow/dags/dag.py
[2025-01-24T23:05:34.734+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-01-24T23:05:34.743+0000] {logging_mixin.py:190} INFO - [2025-01-24T23:05:34.742+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-01-24T23:05:34.785+0000] {logging_mixin.py:190} INFO - [2025-01-24T23:05:34.773+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 11, in <module>
    prim_pipeline_dag = prim_pipelines()
                        ^^^^^^^^^^^^^^^^
TypeError: dag.<locals>.wrapper() missing 1 required positional argument: 'f'
[2025-01-24T23:05:34.788+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-01-24T23:05:34.848+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.133 seconds
[2025-01-24T23:06:07.856+0000] {processor.py:186} INFO - Started process (PID=95) to work on /opt/airflow/dags/dag.py
[2025-01-24T23:06:07.860+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-01-24T23:06:07.872+0000] {logging_mixin.py:190} INFO - [2025-01-24T23:06:07.868+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-01-24T23:06:08.158+0000] {logging_mixin.py:190} INFO - [2025-01-24T23:06:08.150+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 11, in <module>
    prim_pipeline_dag = prim_pipelines()
                        ^^^^^^^^^^^^^^^^
TypeError: dag.<locals>.wrapper() missing 1 required positional argument: 'f'
[2025-01-24T23:06:08.168+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-01-24T23:06:08.205+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.372 seconds
[2025-01-24T23:06:38.486+0000] {processor.py:186} INFO - Started process (PID=102) to work on /opt/airflow/dags/dag.py
[2025-01-24T23:06:38.488+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-01-24T23:06:38.493+0000] {logging_mixin.py:190} INFO - [2025-01-24T23:06:38.493+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-01-24T23:06:38.531+0000] {logging_mixin.py:190} INFO - [2025-01-24T23:06:38.522+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 11, in <module>
    prim_pipeline_dag = prim_pipelines()
                        ^^^^^^^^^^^^^^^^
TypeError: dag.<locals>.wrapper() missing 1 required positional argument: 'f'
[2025-01-24T23:06:38.534+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-01-24T23:06:38.561+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.088 seconds
[2025-01-24T23:07:08.865+0000] {processor.py:186} INFO - Started process (PID=109) to work on /opt/airflow/dags/dag.py
[2025-01-24T23:07:08.867+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-01-24T23:07:08.873+0000] {logging_mixin.py:190} INFO - [2025-01-24T23:07:08.872+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-01-24T23:07:08.903+0000] {logging_mixin.py:190} INFO - [2025-01-24T23:07:08.897+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 11, in <module>
    prim_pipeline_dag = prim_pipelines()
                        ^^^^^^^^^^^^^^^^
TypeError: dag.<locals>.wrapper() missing 1 required positional argument: 'f'
[2025-01-24T23:07:08.906+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-01-24T23:07:08.936+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.081 seconds
[2025-01-24T23:07:39.285+0000] {processor.py:186} INFO - Started process (PID=116) to work on /opt/airflow/dags/dag.py
[2025-01-24T23:07:39.287+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-01-24T23:07:39.292+0000] {logging_mixin.py:190} INFO - [2025-01-24T23:07:39.291+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-01-24T23:07:39.330+0000] {logging_mixin.py:190} INFO - [2025-01-24T23:07:39.314+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 11, in <module>
    prim_pipeline_dag = prim_pipelines()
                        ^^^^^^^^^^^^^^^^
TypeError: dag.<locals>.wrapper() missing 1 required positional argument: 'f'
[2025-01-24T23:07:39.333+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-01-24T23:07:39.362+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.103 seconds
[2025-01-24T23:08:10.315+0000] {processor.py:186} INFO - Started process (PID=123) to work on /opt/airflow/dags/dag.py
[2025-01-24T23:08:10.319+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-01-24T23:08:10.331+0000] {logging_mixin.py:190} INFO - [2025-01-24T23:08:10.330+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-01-24T23:08:10.382+0000] {logging_mixin.py:190} INFO - [2025-01-24T23:08:10.371+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 11, in <module>
    prim_pipeline_dag = prim_pipelines()
                        ^^^^^^^^^^^^^^^^
TypeError: dag.<locals>.wrapper() missing 1 required positional argument: 'f'
[2025-01-24T23:08:10.386+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-01-24T23:08:10.442+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.150 seconds
[2025-01-24T23:08:40.623+0000] {processor.py:186} INFO - Started process (PID=124) to work on /opt/airflow/dags/dag.py
[2025-01-24T23:08:40.627+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-01-24T23:08:40.638+0000] {logging_mixin.py:190} INFO - [2025-01-24T23:08:40.636+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-01-24T23:08:40.678+0000] {logging_mixin.py:190} INFO - [2025-01-24T23:08:40.668+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 11, in <module>
    prim_pipeline_dag = prim_pipelines()
                        ^^^^^^^^^^^^^^^^
TypeError: dag.<locals>.wrapper() missing 1 required positional argument: 'f'
[2025-01-24T23:08:40.682+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-01-24T23:08:40.737+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.143 seconds
[2025-01-24T23:09:11.721+0000] {processor.py:186} INFO - Started process (PID=131) to work on /opt/airflow/dags/dag.py
[2025-01-24T23:09:11.725+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-01-24T23:09:11.740+0000] {logging_mixin.py:190} INFO - [2025-01-24T23:09:11.738+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-01-24T23:09:11.807+0000] {logging_mixin.py:190} INFO - [2025-01-24T23:09:11.790+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 11, in <module>
    prim_pipeline_dag = prim_pipelines()
                        ^^^^^^^^^^^^^^^^
TypeError: dag.<locals>.wrapper() missing 1 required positional argument: 'f'
[2025-01-24T23:09:11.813+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-01-24T23:09:11.890+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.194 seconds
[2025-01-24T23:09:42.042+0000] {processor.py:186} INFO - Started process (PID=138) to work on /opt/airflow/dags/dag.py
[2025-01-24T23:09:42.044+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-01-24T23:09:42.051+0000] {logging_mixin.py:190} INFO - [2025-01-24T23:09:42.050+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-01-24T23:09:42.095+0000] {logging_mixin.py:190} INFO - [2025-01-24T23:09:42.085+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 11, in <module>
    prim_pipeline_dag = prim_pipelines()
                        ^^^^^^^^^^^^^^^^
TypeError: dag.<locals>.wrapper() missing 1 required positional argument: 'f'
[2025-01-24T23:09:42.099+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-01-24T23:09:42.145+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.118 seconds
[2025-01-24T23:16:22.647+0000] {processor.py:186} INFO - Started process (PID=62) to work on /opt/airflow/dags/dag.py
[2025-01-24T23:16:22.649+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-01-24T23:16:22.658+0000] {logging_mixin.py:190} INFO - [2025-01-24T23:16:22.657+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-01-24T23:16:22.685+0000] {logging_mixin.py:190} INFO - [2025-01-24T23:16:22.679+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 11, in <module>
    prim_pipeline_dag = prim_pipelines()
                        ^^^^^^^^^^^^^^^^
TypeError: dag.<locals>.wrapper() missing 1 required positional argument: 'f'
[2025-01-24T23:16:22.688+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-01-24T23:16:22.774+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.221 seconds
[2025-01-24T23:16:53.703+0000] {processor.py:186} INFO - Started process (PID=69) to work on /opt/airflow/dags/dag.py
[2025-01-24T23:16:53.717+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-01-24T23:16:53.775+0000] {logging_mixin.py:190} INFO - [2025-01-24T23:16:53.764+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-01-24T23:16:53.845+0000] {logging_mixin.py:190} INFO - [2025-01-24T23:16:53.829+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 11, in <module>
    prim_pipeline_dag = prim_pipelines()
                        ^^^^^^^^^^^^^^^^
TypeError: dag.<locals>.wrapper() missing 1 required positional argument: 'f'
[2025-01-24T23:16:53.850+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-01-24T23:16:53.979+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.362 seconds
[2025-01-24T23:17:24.213+0000] {processor.py:186} INFO - Started process (PID=77) to work on /opt/airflow/dags/dag.py
[2025-01-24T23:17:24.216+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-01-24T23:17:24.228+0000] {logging_mixin.py:190} INFO - [2025-01-24T23:17:24.227+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-01-24T23:17:24.290+0000] {logging_mixin.py:190} INFO - [2025-01-24T23:17:24.274+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 11, in <module>
    prim_pipeline_dag = prim_pipelines()
                        ^^^^^^^^^^^^^^^^
TypeError: dag.<locals>.wrapper() missing 1 required positional argument: 'f'
[2025-01-24T23:17:24.297+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-01-24T23:17:24.412+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.223 seconds
[2025-01-24T23:17:54.689+0000] {processor.py:186} INFO - Started process (PID=84) to work on /opt/airflow/dags/dag.py
[2025-01-24T23:17:54.692+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-01-24T23:17:54.701+0000] {logging_mixin.py:190} INFO - [2025-01-24T23:17:54.700+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-01-24T23:17:54.740+0000] {logging_mixin.py:190} INFO - [2025-01-24T23:17:54.731+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 11, in <module>
    prim_pipeline_dag = prim_pipelines()
                        ^^^^^^^^^^^^^^^^
TypeError: dag.<locals>.wrapper() missing 1 required positional argument: 'f'
[2025-01-24T23:17:54.745+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-01-24T23:17:54.792+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.130 seconds
[2025-01-24T23:18:25.359+0000] {processor.py:186} INFO - Started process (PID=86) to work on /opt/airflow/dags/dag.py
[2025-01-24T23:18:25.360+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-01-24T23:18:25.368+0000] {logging_mixin.py:190} INFO - [2025-01-24T23:18:25.367+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-01-24T23:18:25.409+0000] {logging_mixin.py:190} INFO - [2025-01-24T23:18:25.397+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 11, in <module>
    prim_pipeline_dag = prim_pipelines()
                        ^^^^^^^^^^^^^^^^
TypeError: dag.<locals>.wrapper() missing 1 required positional argument: 'f'
[2025-01-24T23:18:25.414+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-01-24T23:18:25.500+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.165 seconds
[2025-01-24T23:18:56.315+0000] {processor.py:186} INFO - Started process (PID=92) to work on /opt/airflow/dags/dag.py
[2025-01-24T23:18:56.322+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-01-24T23:18:56.334+0000] {logging_mixin.py:190} INFO - [2025-01-24T23:18:56.332+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-01-24T23:18:56.392+0000] {logging_mixin.py:190} INFO - [2025-01-24T23:18:56.376+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 11, in <module>
    prim_pipeline_dag = prim_pipelines()
                        ^^^^^^^^^^^^^^^^
TypeError: dag.<locals>.wrapper() missing 1 required positional argument: 'f'
[2025-01-24T23:18:56.401+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-01-24T23:18:56.445+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.159 seconds
[2025-01-24T23:19:26.877+0000] {processor.py:186} INFO - Started process (PID=99) to work on /opt/airflow/dags/dag.py
[2025-01-24T23:19:26.879+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-01-24T23:19:26.884+0000] {logging_mixin.py:190} INFO - [2025-01-24T23:19:26.883+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-01-24T23:19:26.919+0000] {logging_mixin.py:190} INFO - [2025-01-24T23:19:26.910+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 11, in <module>
    prim_pipeline_dag = prim_pipelines()
                        ^^^^^^^^^^^^^^^^
TypeError: dag.<locals>.wrapper() missing 1 required positional argument: 'f'
[2025-01-24T23:19:26.923+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-01-24T23:19:26.959+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.102 seconds
[2025-01-24T23:19:58.746+0000] {processor.py:186} INFO - Started process (PID=106) to work on /opt/airflow/dags/dag.py
[2025-01-24T23:19:58.748+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-01-24T23:19:58.753+0000] {logging_mixin.py:190} INFO - [2025-01-24T23:19:58.753+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-01-24T23:19:58.792+0000] {logging_mixin.py:190} INFO - [2025-01-24T23:19:58.782+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 11, in <module>
    prim_pipeline_dag = prim_pipelines()
                        ^^^^^^^^^^^^^^^^
TypeError: dag.<locals>.wrapper() missing 1 required positional argument: 'f'
[2025-01-24T23:19:58.796+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-01-24T23:19:58.841+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.108 seconds
[2025-01-24T23:20:29.323+0000] {processor.py:186} INFO - Started process (PID=113) to work on /opt/airflow/dags/dag.py
[2025-01-24T23:20:29.326+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-01-24T23:20:29.330+0000] {logging_mixin.py:190} INFO - [2025-01-24T23:20:29.330+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-01-24T23:20:29.361+0000] {logging_mixin.py:190} INFO - [2025-01-24T23:20:29.354+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 11, in <module>
    prim_pipeline_dag = prim_pipelines()
                        ^^^^^^^^^^^^^^^^
TypeError: dag.<locals>.wrapper() missing 1 required positional argument: 'f'
[2025-01-24T23:20:29.364+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-01-24T23:20:29.394+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.092 seconds
[2025-01-24T23:20:59.555+0000] {processor.py:186} INFO - Started process (PID=120) to work on /opt/airflow/dags/dag.py
[2025-01-24T23:20:59.557+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-01-24T23:20:59.562+0000] {logging_mixin.py:190} INFO - [2025-01-24T23:20:59.561+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-01-24T23:20:59.593+0000] {logging_mixin.py:190} INFO - [2025-01-24T23:20:59.586+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 11, in <module>
    prim_pipeline_dag = prim_pipelines()
                        ^^^^^^^^^^^^^^^^
TypeError: dag.<locals>.wrapper() missing 1 required positional argument: 'f'
[2025-01-24T23:20:59.596+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-01-24T23:20:59.624+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.081 seconds
[2025-01-24T23:21:29.756+0000] {processor.py:186} INFO - Started process (PID=127) to work on /opt/airflow/dags/dag.py
[2025-01-24T23:21:29.758+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-01-24T23:21:29.762+0000] {logging_mixin.py:190} INFO - [2025-01-24T23:21:29.762+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-01-24T23:21:29.789+0000] {logging_mixin.py:190} INFO - [2025-01-24T23:21:29.782+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 11, in <module>
    prim_pipeline_dag = prim_pipelines()
                        ^^^^^^^^^^^^^^^^
TypeError: dag.<locals>.wrapper() missing 1 required positional argument: 'f'
[2025-01-24T23:21:29.791+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-01-24T23:21:29.820+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.072 seconds
[2025-01-24T23:22:00.529+0000] {processor.py:186} INFO - Started process (PID=134) to work on /opt/airflow/dags/dag.py
[2025-01-24T23:22:00.532+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-01-24T23:22:00.545+0000] {logging_mixin.py:190} INFO - [2025-01-24T23:22:00.543+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-01-24T23:22:00.606+0000] {logging_mixin.py:190} INFO - [2025-01-24T23:22:00.585+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 11, in <module>
    prim_pipeline_dag = prim_pipelines()
                        ^^^^^^^^^^^^^^^^
TypeError: dag.<locals>.wrapper() missing 1 required positional argument: 'f'
[2025-01-24T23:22:00.612+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-01-24T23:22:00.677+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.183 seconds
[2025-01-24T23:22:31.418+0000] {processor.py:186} INFO - Started process (PID=142) to work on /opt/airflow/dags/dag.py
[2025-01-24T23:22:31.425+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-01-24T23:22:31.437+0000] {logging_mixin.py:190} INFO - [2025-01-24T23:22:31.436+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-01-24T23:22:31.500+0000] {logging_mixin.py:190} INFO - [2025-01-24T23:22:31.486+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 11, in <module>
    prim_pipeline_dag = prim_pipelines()
                        ^^^^^^^^^^^^^^^^
TypeError: dag.<locals>.wrapper() missing 1 required positional argument: 'f'
[2025-01-24T23:22:31.507+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-01-24T23:22:31.592+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.204 seconds
[2025-01-24T23:23:02.024+0000] {processor.py:186} INFO - Started process (PID=150) to work on /opt/airflow/dags/dag.py
[2025-01-24T23:23:02.026+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-01-24T23:23:02.032+0000] {logging_mixin.py:190} INFO - [2025-01-24T23:23:02.031+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-01-24T23:23:02.062+0000] {logging_mixin.py:190} INFO - [2025-01-24T23:23:02.055+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 11, in <module>
    prim_pipeline_dag = prim_pipelines()
                        ^^^^^^^^^^^^^^^^
TypeError: dag.<locals>.wrapper() missing 1 required positional argument: 'f'
[2025-01-24T23:23:02.066+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-01-24T23:23:02.108+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.092 seconds
[2025-01-24T23:23:32.566+0000] {processor.py:186} INFO - Started process (PID=157) to work on /opt/airflow/dags/dag.py
[2025-01-24T23:23:32.570+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-01-24T23:23:32.578+0000] {logging_mixin.py:190} INFO - [2025-01-24T23:23:32.577+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-01-24T23:23:32.646+0000] {logging_mixin.py:190} INFO - [2025-01-24T23:23:32.629+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 11, in <module>
    prim_pipeline_dag = prim_pipelines()
                        ^^^^^^^^^^^^^^^^
TypeError: dag.<locals>.wrapper() missing 1 required positional argument: 'f'
[2025-01-24T23:23:32.653+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-01-24T23:23:32.722+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.195 seconds
[2025-01-24T23:57:42.836+0000] {processor.py:186} INFO - Started process (PID=67) to work on /opt/airflow/dags/dag.py
[2025-01-24T23:57:42.839+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-01-24T23:57:42.843+0000] {logging_mixin.py:190} INFO - [2025-01-24T23:57:42.842+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-01-24T23:57:42.873+0000] {logging_mixin.py:190} INFO - [2025-01-24T23:57:42.863+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 11, in <module>
    prim_pipeline_dag = prim_pipelines()
                        ^^^^^^^^^^^^^^^^
TypeError: dag.<locals>.wrapper() missing 1 required positional argument: 'f'
[2025-01-24T23:57:42.876+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-01-24T23:57:42.923+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.097 seconds
[2025-01-24T23:58:16.322+0000] {processor.py:186} INFO - Started process (PID=129) to work on /opt/airflow/dags/dag.py
[2025-01-24T23:58:16.324+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-01-24T23:58:16.337+0000] {logging_mixin.py:190} INFO - [2025-01-24T23:58:16.336+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-01-24T23:58:16.368+0000] {logging_mixin.py:190} INFO - [2025-01-24T23:58:16.360+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 11, in <module>
    prim_pipeline_dag = prim_pipelines()
                        ^^^^^^^^^^^^^^^^
TypeError: dag.<locals>.wrapper() missing 1 required positional argument: 'f'
[2025-01-24T23:58:16.370+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-01-24T23:58:16.466+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.173 seconds
[2025-01-24T23:58:49.009+0000] {processor.py:186} INFO - Started process (PID=192) to work on /opt/airflow/dags/dag.py
[2025-01-24T23:58:49.012+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-01-24T23:58:49.020+0000] {logging_mixin.py:190} INFO - [2025-01-24T23:58:49.019+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-01-24T23:58:49.047+0000] {logging_mixin.py:190} INFO - [2025-01-24T23:58:49.042+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 11, in <module>
    prim_pipeline_dag = prim_pipelines()
                        ^^^^^^^^^^^^^^^^
TypeError: dag.<locals>.wrapper() missing 1 required positional argument: 'f'
[2025-01-24T23:58:49.048+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-01-24T23:58:49.078+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.081 seconds
[2025-01-24T23:59:22.517+0000] {processor.py:186} INFO - Started process (PID=255) to work on /opt/airflow/dags/dag.py
[2025-01-24T23:59:22.518+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-01-24T23:59:22.521+0000] {logging_mixin.py:190} INFO - [2025-01-24T23:59:22.521+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-01-24T23:59:22.540+0000] {logging_mixin.py:190} INFO - [2025-01-24T23:59:22.536+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 11, in <module>
    prim_pipeline_dag = prim_pipelines()
                        ^^^^^^^^^^^^^^^^
TypeError: dag.<locals>.wrapper() missing 1 required positional argument: 'f'
[2025-01-24T23:59:22.542+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-01-24T23:59:22.561+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.049 seconds
