[2025-01-26T02:23:03.298+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-26T02:23:03.316+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: prim_pipelines.get_data_from_prim_api manual__2025-01-26T02:08:37.846460+00:00 [queued]>
[2025-01-26T02:23:03.324+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: prim_pipelines.get_data_from_prim_api manual__2025-01-26T02:08:37.846460+00:00 [queued]>
[2025-01-26T02:23:03.324+0000] {taskinstance.py:2866} INFO - Starting attempt 2 of 2
[2025-01-26T02:23:03.338+0000] {taskinstance.py:2889} INFO - Executing <Task(_PythonDecoratedOperator): get_data_from_prim_api> on 2025-01-26 02:08:37.846460+00:00
[2025-01-26T02:23:03.345+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=728) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-26T02:23:03.347+0000] {standard_task_runner.py:72} INFO - Started process 743 to run task
[2025-01-26T02:23:03.347+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'prim_pipelines', 'get_data_from_prim_api', 'manual__2025-01-26T02:08:37.846460+00:00', '--job-id', '39', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmp40feuoxn']
[2025-01-26T02:23:03.348+0000] {standard_task_runner.py:105} INFO - Job 39: Subtask get_data_from_prim_api
[2025-01-26T02:23:03.392+0000] {task_command.py:467} INFO - Running <TaskInstance: prim_pipelines.get_data_from_prim_api manual__2025-01-26T02:08:37.846460+00:00 [running]> on host d9d6adeb4aac
[2025-01-26T02:23:03.482+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='prim_pipelines' AIRFLOW_CTX_TASK_ID='get_data_from_prim_api' AIRFLOW_CTX_EXECUTION_DATE='2025-01-26T02:08:37.846460+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-26T02:08:37.846460+00:00'
[2025-01-26T02:23:03.484+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-26T02:23:04.045+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-01-26T02:23:04.055+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-26T02:23:04.057+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=prim_pipelines, task_id=get_data_from_prim_api, run_id=manual__2025-01-26T02:08:37.846460+00:00, execution_date=20250126T020837, start_date=20250126T022303, end_date=20250126T022304
[2025-01-26T02:23:04.084+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-26T02:23:04.116+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-01-26T02:23:04.117+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
